version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/laraveltest/
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/permission.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root

